### ISSUE TITLE
Troubles with JSON

### ISSUE THREAD

**Issue by botsbuzz** [NadzeyaD/YarnClone#1]
The server were the JSON file is store is down (http://spookytalks.com/files/stories.json).

Any idea to solve the issue?

Thank you,

Stefano

**Comment by NadzeyaD** [comment]
Hi Stefano, 
Unfortunately I'm not owner of this link: this project was created as test task for company and they provided this link. I  can suggest you to create your own json with format described in StoryHeader model (for list of stories) and in StoryMessage model (for story messages) (func mapping). And I'll try to replace links on working json soon.

Nadia

**Comment by NadzeyaD** [comment]
Hi Stefano,

I've just added test jsons, created by myself.

Nadia
